# Generated by Django 4.2.6 on 2023-12-06 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Course_Thumbnail')),
                ('author', models.TextField(default='Murengezi Dieudone')),
                ('created_at', models.TimeField(verbose_name=datetime.datetime(2023, 12, 6, 9, 43, 48, 832974, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
