# Generated by Django 4.2.6 on 2023-12-06 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.CharField(default='Murengezi Dieudone', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2023, 12, 6, 9, 47, 13, 864188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
