# Generated by Django 4.2.6 on 2023-12-06 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_alter_course_author_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 12, 6, 12, 11, 45, 378662, tzinfo=datetime.timezone.utc)),
        ),
    ]
