# Generated by Django 4.2.6 on 2023-12-08 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0005_alter_course_created_at_chapter_skills_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 12, 8, 6, 10, 0, 720093, tzinfo=datetime.timezone.utc)),
        ),
    ]
