# Generated by Django 4.2.6 on 2023-12-08 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_remove_skills_chapter_alter_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Staff.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2023, 12, 8, 6, 11, 0, 122588, tzinfo=datetime.timezone.utc)),
        ),
    ]
