# Generated by Django 4.2.6 on 2024-01-08 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_alter_chapter_id_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2024, 1, 8, 17, 15, 50, 180875, tzinfo=datetime.timezone.utc)),
        ),
    ]
