# Generated by Django 4.2.6 on 2024-01-16 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0013_team_alter_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='Team_profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 16, 31, 31, 178425, tzinfo=datetime.timezone.utc)),
        ),
    ]
